version: "3.7"
services:
  db:
    image: mysql:5.7
    container_name: future-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: RootDifficultPassword
      MYSQL_PASSWORD: DifficultPassword
      MYSQL_USER: homestead
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - future

  app:
    build:
      args:
        user: phat
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: future
    container_name: future-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./www/:/var/www
    networks:
      - future

  nginx:
    image: nginx:alpine
    container_name: future-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./www/:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - future

  api:
    build:
      args:
        user: phat
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: future
    container_name: future-api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./api/:/var/www
    networks:
      - future

  nginx_api:
    image: nginx:alpine
    container_name: future-nginx-api
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./api/:/var/www
      - ./nginx/api.conf:/etc/nginx/conf.d/default.conf
    networks:
      - future

networks:
  future:
    driver: bridge